project_id = "ycbftnwzoxktoroqpslo"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.resend-otp]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false